import type { Config } from "tailwindcss";

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Public site colors
        primary: "#00BCD4",
        "primary-light": "#00daf3",
        "on-primary": "#000000",
        background: "#05070a",
        surface: "#0a0c10",
        "surface-variant": "#12141a",
        outline: "#2d3139",
        "on-background": "#ffffff",
        "on-surface-variant": "#94a3b8",
        
        // Admin/MD3 colors
        "surface-dim": "#111318",
        "on-background-dim": "#e2e2e8",
        "tertiary-fixed-dim": "#94d3c1",
        "tertiary-container": "#79b7a6",
        "on-primary-fixed": "#001f24",
        "on-tertiary": "#00382e",
        "outline-admin": "#869396",
        error: "#ffb4ab",
        "on-surface-variant-admin": "#bbc9cc",
        "background-admin": "#111318",
        "primary-admin": "#00daf3",
        "outline-variant": "#3c494c",
        "on-primary-fixed-variant": "#004f58",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#065043",
        "surface-admin": "#111318",
        "inverse-on-surface": "#2f3035",
        "inverse-primary": "#006875",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#282a2e",
        "surface-bright": "#37393e",
        "secondary-fixed": "#c9e8ef",
        "on-error": "#690005",
        "primary-container": "#00bcd2",
        "surface-container": "#1e2024",
        "on-secondary-fixed-variant": "#2e4b51",
        "surface-variant-admin": "#333539",
        "primary-fixed": "#9cf0ff",
        secondary: "#adccd2",
        "surface-container-low": "#1a1c20",
        "on-tertiary-fixed": "#00201a",
        "surface-container-lowest": "#0c0e12",
        "surface-container-highest": "#333539",
        "surface-tint": "#00daf3",
        "secondary-container": "#2e4b51",
        tertiary: "#94d3c1",
        "on-secondary-container": "#9cbac1",
        "secondary-fixed-dim": "#adccd2",
        "on-primary-container": "#004750",
        "on-surface-admin": "#e2e2e8",
        "on-secondary-fixed": "#001f24",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary-container": "#00483c",
        "on-secondary": "#17353a",
        "on-primary-admin": "#00363d",
        "tertiary-fixed": "#afefdd",
        "inverse-surface": "#e2e2e8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
        // Admin-specific radius
        "sm-admin": "0.125rem",
        "full-admin": "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
